### ISSUE TITLE
How to add other food for the horses

### ISSUE THREAD

**Issue by Gentil-Boo** [CryptoGenics/cryptos_horses#3]
I see this line

`Config.FeedItem = 'wildcarrot' `

And I want to add apple item in the list. how can I do this, i tried 

`Config.FeedItem = 'wildcarrot' , 'apple'`

but not working

**Comment by CryptoGenics** [comment]
Changed to Config.FeedItems you can now add items to the feed items table instead of 1 specific item.

**Comment by Gentil-Boo** [comment]
Realy? You've aded this to your code? thank you

`Config.FeedItems = 'wildcarrot' , 'apple'`

Like this ? it is the good syntax ?
