### ISSUE TITLE
Any way to make the range smaller?

### ISSUE THREAD

**Issue by TheDevster** [CryptoGenics/cryptos_horses#4]
First, Thanks for this script.  I am wonder if there is a way to create the range for creating the prompts to be smaller (IE: closer to a horse before you get the prompts).   I thought it was line# 10 in client.lua (local size = ), but no matter how much I adjust that I cannot seem to get the range to be closer.  Perhaps I am misunderstanding the native but I am unable to find good documentation on it.

**Comment by CryptoGenics** [comment]
There is no way to do this with the way the prompts are setup. The way the prompts are written right now they are added to the horse prompt group itself natively, not appearing when focusing or something like other 'prompts'.

**Comment by TheDevster** [comment]
I appreciate your answer.. I'm new to REDM/Fivem (and LUA in general) so still trying to learn things (though I've been writing software for 30 years now).  Can you help me understand what your loop is doing? There is a piece that is dodgy for me, after that I piece I recognize that it compares entity model with horse model to see if they are the same and then adds the prompts?

I wish there was better documentation, especially for native calls.. there are so many natives but they lack documentation to explain what they do.  Anyhow I really appreciate you answering my previous question.

**Comment by CryptoGenics** [comment]
CreateItemset loop?

**Comment by CryptoGenics** [comment]
I just used what key_value posted to enumerate through entities nearby. https://discord.com/channels/192358910387159041/643437814104457217/705079551176343592

**Comment by TheDevster** [comment]
Thanks man.. Appreciate the help!
